trigger:
  branches:
    include:
    - main

pool:
  vmImage: ubuntu-latest

variables:
  function-folder: "apps/api"
  webapp-folder: "apps/web"

stages:
- stage: Build
  jobs:
  - job: PNPM
    steps:
      - task: NodeTool@0 
        inputs:
          versionSpec: '14.x'
        
      - script: |
          npm install -g pnpm
          rm .npmrc
          pnpm config set node-linker hoisted
        displayName: "Setup pnpm" 

      # BUG : To analyze, not only api project dependencies installed in the root node_modules (see nuxt) no matter "recursive-install false"
      - script: pnpm --filter api install
        displayName: "Install dependencies"   

      # CONTROL API DEPS
      - script: ls -l $(function-folder)/node_modules
        displayName: "CONTROL API DEPS" # Should contain all deps for api or no symlinks

      # CONTROL ROOT node_modules
      - script: ls -l node_modules
        displayName: "CONTROL ROOT node_modules" # Should be empty and NOT contain web deps
          
      # API ARTIFACT | copy complete folder recursively (pnpm deploy doesn't work to provide all node_modules dependencies)
      - script: cp -rL $(function-folder) $(Build.ArtifactStagingDirectory)/api-cp
        displayName: "Bundle"

      # CONTROL BUNDLE DEPS
      - script: ls -l $(Build.ArtifactStagingDirectory)/api/node_modules
        displayName: "CONTROL BUNDLE DEPS" # Should contain all deps for api

      # PNPM Deploy
      - script: pnpm --filter=api deploy $(Build.ArtifactStagingDirectory)/api-bundle
        displayName: "Pnpm deploy"

      # CONTROL PNPM Deploy
      - script: ls -l $(Build.ArtifactStagingDirectory)/api-bundle/node_modules
        displayName: "CONTROL PNPM Deploy DEPS" # Should contain all deps for api
      

      - task: PublishBuildArtifacts@1
        displayName: "Publish artifact"
        inputs:
          PathtoPublish: $(Build.ArtifactStagingDirectory)
          ArtifactName: 'api'
          publishLocation: 'Container'
          StoreAsTar: false

  - job: YARN
    steps:
      - task: NodeTool@0 
        inputs:
          versionSpec: '14.x'
        
      - script: yarn install
        displayName: "Install dependencies"
      

      - task: PublishBuildArtifacts@1
        displayName: "Publish artifact"
        inputs:
          PathtoPublish: $(Build.ArtifactStagingDirectory)
          ArtifactName: 'api'
          publishLocation: 'Container'
          StoreAsTar: false


- stage: Test
  jobs:
  - job: TODO
    steps:
      - script: echo "no tests, just sample"
        displayName: "Tests" 